### ISSUE TITLE
Selenium 4.10.0 is not compatible with the current undetected_chromedriver 3.4.7

### ISSUE THREAD

**Issue by ruzrobert** [ultrafunkamsterdam/undetected-chromedriver#1318]
Hi!
After upgrading to the Seleniun 4.10.0 (last version) getting this error when trying to start the undetected_chromedriver (3.4.7):
`Catched exc "TypeError": __init__() got an unexpected keyword argument 'executable_path'
	1) File "/var/apps/venv/lib/python3.9/site-packages/undetected_chromedriver/__init__.py", line 453`

**Comment by mdmintz** [comment]
The deprecated methods from ``selenium`` have been removed:
https://github.com/SeleniumHQ/selenium/commit/9f5801c82fb3be3d5850707c46c3f8176e3ccd8e

<img width="1403" alt="Screenshot 2023-06-07 at 3 05 04 PM" src="https://github.com/ultrafunkamsterdam/undetected-chromedriver/assets/6788579/e4d33bdf-3ba2-4d56-8855-9dc09b370c48"><br />

 In order to resolve this issue via ``undetected-chromedriver``, the removed parameters will need to be passed in via ``Options`` or ``Service``. Otherwise this repo is broken unless ``selenium`` is pinned to ``4.9.1`` in the meantime.

**Comment by HugoLunel** [comment]
Alternative fix is to force use selenium 4.9 in the virtual env

**Comment by t3ch-support** [comment]
I can confirm this, however pinning selenium to 4.9 breaks with the current version of Chrome: 

` This version of ChromeDriver only supports Chrome version 112
Current browser version is 114.0.5735.110`

**Comment by mdmintz** [comment]
@t3ch-support See the undetected-chromedriver ReadMe. Your issue can be resolved by setting ``version_main`` to the major browser version, (eg ``114``), when calling ``uc.Chrome()``. Eg. ``driver=uc.Chrome(version_main=114)``. ``selenium`` can be pinned safely to ``4.9.1`` without issue if done correctly.

**Comment by ultrafunkamsterdam** [comment]
Please test 3.5.0 branch someone ?

**Comment by SKnight79** [comment]
worked for me:
pip uninstall selenium
pip install selenium==4.9.1

**Comment by GuanLong-Lyu** [comment]
After I changed the version of selenium from 4.10.0 to 4.9.1, still got the same error.

selenium                               4.9.1
undetected-chromedriver  3.4.7

**Comment by ruzrobert** [comment]
@GuanLong-Lyu works for me, Python 3.9, virtualenv

**Comment by GuanLong-Lyu** [comment]
> @GuanLong-Lyu works for me, Python 3.9, virtualenv

Thanks for the reply! I'm using Python 3.7.9, virtualenv. But not sure if this issue is caused by Python version.

**Comment by GuanLong-Lyu** [comment]
> > @GuanLong-Lyu works for me, Python 3.9, virtualenv
> 
> Thanks for the reply! I'm using Python 3.7.9, virtualenv. But not sure if this issue is caused by Python version.

Never mind, the issue was solved by rebooting. :)

**Comment by dustinfarris** [comment]
> Please test 3.5.0 branch someone ?

3.5.0 works for me 👍

**Comment by GISH123** [comment]
> @t3ch-support See the undetected-chromedriver ReadMe. Your issue can be resolved by setting `version_main` to the major browser version, (eg `114`), when calling `uc.Chrome()`. Eg. `driver=uc.Chrome(version_main=114)`. `selenium` can be pinned safely to `4.9.1` without issue if done correctly.


my code still breaks, im testing every method i can, but still it still shows the error:

![image](https://github.com/ultrafunkamsterdam/undetected-chromedriver/assets/4023299/d7249dc6-5faa-4da4-ae1e-12387a2bbb22)
can anyone help me 😢😢

**Comment by ultrafunkamsterdam** [comment]
update to 3.5.0 
```
pip uninstall undetected-chromedriver 
select yes 
pip install -U undetected-chromedriver
```

**Comment by GISH123** [comment]
> update to 3.5.0
> 
> ```
> pip uninstall undetected-chromedriver 
> select yes 
> pip install -U undetected-chromedriver
> ```

Very mcu appreciated!

**Comment by GISH123** [comment]
> update to 3.5.0
> 
> ```
> pip uninstall undetected-chromedriver 
> select yes 
> pip install -U undetected-chromedriver
> ```

After doing this, i still have the same issue though....

my UC  is already 3.5.0

![image](https://github.com/ultrafunkamsterdam/undetected-chromedriver/assets/4023299/788ab2f3-c210-4291-82fc-b5adb68ddc34)


What did i miss?

**Comment by Romhast** [comment]
> > update to 3.5.0
> > ```
> > pip uninstall undetected-chromedriver 
> > select yes 
> > pip install -U undetected-chromedriver
> > ```
> 
> After doing this, i still have the same issue though....
> 
> my UC is already 3.5.0
> 
> ![image](https://user-images.githubusercontent.com/4023299/245341201-788ab2f3-c210-4291-82fc-b5adb68ddc34.png)
> 
> What did i miss?

same problem, my uc 3.5.0

**Comment by mdmintz** [comment]
I think ``undetected-chromedriver`` can benefit from autodetecting the browser version so that specifying ``version_main`` isn't required. I already have the code for that, which I borrowed from selenium manager: https://github.com/seleniumbase/SeleniumBase/blob/master/seleniumbase/core/detect_b_ver.py

I combined that with UC Mode into ``SeleniumBase`` so that it simplifies setup.

```python
from seleniumbase import Driver
import time

driver = Driver(uc_cdp=True, incognito=True)
driver.get("https://nowsecure.nl/#relax")
time.sleep(8)
driver.quit()
```

With [detect_b_ver.py](https://github.com/seleniumbase/SeleniumBase/blob/master/seleniumbase/core/detect_b_ver.py), people will no longer need to specify the browser/driver version themselves.

**Comment by Prakash2403** [comment]
@Spykerwolf Have you tried setting `version_main=114` while initializing. E.g.
```
 driver = uc.Chrome(version_main=114, **kwargs)
```

`version_main` must match the version of chrome executable in your `$PATH`
