### ISSUE TITLE
ModuleNotFoundError: No module named 'distutils'

### ISSUE THREAD

**Issue by Ciccioposticcio** [ultrafunkamsterdam/undetected-chromedriver#1674]
Hi all, 
i'm getting this error today with my project when i try to run it. I use last undetected-chromedriver with Python 3.12 (os is Windows 11 pro). 
Any fix? 

```
File "c:\Users\rober\Desktop\ProgettiPython\main.py", line 21, in <module>
    import undetected_chromedriver as uc
File "C:\Users\rober\Desktop\ProgettiPython\.venv\Lib\site-packages\undetected_chromedriver\__init__.py", line 44, in <module>
    from .patcher import IS_POSIX
File "C:\Users\rober\Desktop\ProgettiPython\.venv\Lib\site-packages\undetected_chromedriver\patcher.py", line 4, in <module>
    from distutils.version import LooseVersion
ModuleNotFoundError: No module named 'distutils'
```

_Originally posted by @Ciccioposticcio in https://github.com/ultrafunkamsterdam/undetected-chromedriver/discussions/1673_

**Comment by Ciccioposticcio** [comment]
Fixed installing _setuptools_ with (pip install --upgrade setuptools) as suggested in https://docs.python.org/3.12/whatsnew/3.12.html

**Comment by cubicbyte** [comment]
@Ciccioposticcio It's worth re-opening this issue, since it's still a problem with this library.

The **distutils** has been removed from the python standard library, so the author need to either include setuptools in the dependency list or otherwise migrate to something else

**Comment by Ciccioposticcio** [comment]
@cubicbyte ok I take your advice and reopen the issue

**Comment by Chetan11-dev** [comment]
Hi Everyone, I recommend giving Botasaurus a try. It's an Anti Detection library that will help you bypass bot detection. It also doesn't cause distutils error. Here's how you can use it to visit https://nowsecure.nl/:

1. **Install Botasaurus**
```bash
python -m pip install botasaurus
```

2. **Bypass https://nowsecure.nl/**
```python
from botasaurus import *
from botasaurus.create_stealth_driver import create_stealth_driver

@browser(
    create_driver=create_stealth_driver(
        start_url="https://nowsecure.nl/",
    ),
)
def scrape_heading_task(driver: AntiDetectDriver, data):
    driver.prompt()
    heading = driver.text('h1')
    return heading

scrape_heading_task()    
```

![Now Secure Bypass](https://raw.githubusercontent.com/omkarcloud/botasaurus/master/images/now-secure-bypass.gif)

I suggest learning about bypassing various Cloudflare protections [here.](https://github.com/omkarcloud/botasaurus/tree/master#can-you-bypass-cloudflareimperva-challenges)

## If this has been a lifesaver for you, I would greatly appreciate a [Star here :)](https://github.com/omkarcloud/botasaurus)

**Comment by vxphuongictu** [comment]
I am having the same problem

**Comment by HassanAbbas7357** [comment]
i am facing same problem in Python 3.13

**Comment by Ciccioposticcio** [comment]
Just install setuptools to fix the problem:
`pip install setuptools`
