### ISSUE TITLE
Chrome din't  completes the process in windows

### ISSUE THREAD

**Issue by RussianPostman** [ultrafunkamsterdam/undetected-chromedriver#1767]
<img width="508" alt="image" src="https://github.com/ultrafunkamsterdam/undetected-chromedriver/assets/101946633/2a3057a8-530c-4f07-8338-fb21789f6b66">
After successful completion of any program using undetected-chromedriver, the Chrome process remains. This process consumes a lot of CPU resources and does not do anything visible. 
driver.quit() closes the window, but the process remains and continues to consume resources. 
How do I shut down the program correctly? 
This problem is only with undetected-chromedriver

**Comment by grah48583** [comment]
did you try this?
#1723 

on my pc there is GPU. i had the same issue, i was using the code below then when i tried to disable GPU, issue was resolved.
on my server there is no GPU hence this problem is never occurred.


```
def fml_chrome():
    try:
        # List all running processes
        tasks = subprocess.check_output(['tasklist'], encoding='utf-8')

        # Check and kill Chrome processes if found
        if 'chrome.exe' in tasks:
            subprocess.run(["taskkill", "/F", "/IM", "chrome.exe", "/T"], check=True)
            logging.info("Chrome processes killed.")
        else:
            logging.info("No Chrome processes found.")

        # Check and kill Chromedriver processes if found
        if 'chromedriver.exe' in tasks:
            subprocess.run(["taskkill", "/F", "/IM", "chromedriver.exe", "/T"], check=True)
            logging.info("Chromedriver processes killed.")
        else:
            logging.info("No Chromedriver processes found.")

    except subprocess.CalledProcessError as e:
        logging.error(f"Error checking or killing processes: {e}")
```

**Comment by 0x1991** [comment]
The only way I fixed this issue was calling `close()` before `quit()` like:

```
driver.close()
driver.quit()
```

**Comment by kim-chung-man** [comment]
I too am experiencing the same thing. 
I tried the above suggestions, but it didn't solve the problem.

**Comment by fthmko** [comment]
In my case,  two process keep running after `driver.quit()`.
I found `os.kill(chrome-pid, 15)` will got this result, no matter it's started by driver or just click the icon.

However, windows command `taskkill /pid chrome-pid` works perfect. So this is my solution:

```python
os.system("taskkill /pid " + driver.browser_pid)
while psutil.pid_exists(driver.browser_pid):
    time.sleep(0.1)
driver.quit()
```
