### ISSUE TITLE
NoDriver Python Bug

### ISSUE THREAD

**Issue by ak3zaidan** [ultrafunkamsterdam/undetected-chromedriver#2275]
Hello I am asking this here, since NoDriver is similar but their issues are closed.

I am using [NoDriver](https://github.com/ultrafunkamsterdam/nodriver) python on MacOS and sometimes when I try and open a browser tab it fails with the error below (I've tried Chrome+Chromium and it happens on both). If I manually open the browser and then close it and quit it then retry, this error doesn't happen. This issue only happens on the very first try sometimes if I haven't used chrome/chromium in a while. 

I am using Headful mode. I did try to pass no_sandbox=True but this did nothing. I also tried going into activity monitor and closing all Chrome processes. I also tried to remove Singleton Locks as Ai suggested.

This also happens ANYTIME when I use a chrome profile. I use `start_kwargs["browser_executable_path"] = browser_path` and `args.append(f"--profile-directory={profile_dir}")` and then chrome successfully launches with the profile but then crashes with the same error. However if I use Chromium then the crash doesn't happen and the profile is used successfully.

It seems that the get request `value = await self._http.get("version")` is resulting in `<urlopen error [Errno 61] Connection refused>.`

My Code
```
from nodriver import *

browser = await start(
    headless=False,
    browser_executable_path="/path/to/some/other/browser",
)
tab = await browser.get('https://somewebsite.com')
```

Error
```
                ---------------------
                Failed to connect to browser
                ---------------------
                One of the causes could be when you are running as root.
                In that case you need to pass no_sandbox=True 
                
```

NoDriver Crash Location (In the browser start function):
```
self._http = HTTPApi((self.config.host, self.config.port))
util.get_registered_instances().add(self)
await asyncio.sleep(0.25)
for _ in range(5):
    try:
        # Error HERE
        value = await self._http.get("version")
        # Error HERE
        
        self.info = ContraDict(value, silent=True)
    except Exception as e:
        print(f"Error getting version: {e}")
        if _ == 4:
            logger.debug("could not start", exc_info=True)
        await asyncio.sleep(0.5)
    else:
        break

if not self.info:
    raise Exception(
        (
            """
        ---------------------
        Failed to connect to browser
        ---------------------
        One of the causes could be when you are running as root.
        In that case you need to pass no_sandbox=True 
        """
        )
    )
```

**Comment by devblack** [comment]
Some Chrome features, or maybe the first run, are making the launch slow. So the await asyncio.sleep(0.25) isn’t going to work. You can disable some features using chrome args.

**Comment by ak3zaidan** [comment]
@devblack Thanks, I tried changing the for loop to run 20 times and even with that extended window `self._http.get("version")` was still failing, so Im not sure if its a time issue or not. Which args do you recommend to disable?

**Comment by ultrafunkamsterdam** [comment]
I fixed a bug for posix yesterday. Try update

**Comment by ak3zaidan** [comment]
@ultrafunkamsterdam thanks, tried 0.48.1 but the issue still happens. I tried cloning the user profile dir and using the cloned profile with chrome and it worked. So it seems like the issue is the Singleton Locks based on what the user said: https://stackoverflow.com/a/79816158/18070009. Is there a better way than cloning the profile?

**Comment by ultrafunkamsterdam** [comment]
Also be aware once chrome has started it keeps processes in the background and locks your user profile. Use something like kill -9 $(pidof chrome) or something similar to ensure no bg processes exist before launching

**Comment by ultrafunkamsterdam** [comment]
Else import logging first,.
Then logging.basicConfig(level=10)

Then the rest of your imports and script. Run it and give the output

**Comment by boris-vendom** [comment]
my fix
```
        self._http = HTTPApi((self.config.host, self.config.port))
        util.get_registered_instances().add(self)
        await asyncio.sleep(2)
        for _ in range(5):
            try:
                self.info = ContraDict(await self._http.get("version"), silent=True)
            except (Exception,):
                if _ == 4:
                    logger.debug("could not start", exc_info=True)
                else:
                    if self.info:
                        break
                
            if _ < 4:
                await asyncio.sleep(2)
```

**Comment by ak3zaidan** [comment]
@boris-vendom Your fix just increases the retry period, which actually is better for cold starts as it properly gives the browser more time to start. However it does not fix the main issue with the chrome profile.

@ultrafunkamsterdam Here's the logging output. Also I think you should use @boris-vendom increased delay suggestion.

```
DEBUG:asyncio:Using selector: KqueueSelector
DEBUG:nodriver.core.browser:Session object initialized: {'config': Config
        browser_executable_path = /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
        sandbox = True
        autodiscover_targets = True
        browser_args = ['--disable-breakpad', '--disable-dev-shm-usage', '--disable-infobars', '--disable-search-engine-choice-screen', '--disable-session-crashed-bubble', '--homepage=about:blank', '--no-default-browser-check', '--no-first-run', '--no-pings', '--no-service-autorun', '--password-store=basic', '--profile-directory=Profile 4', '--remote-allow-origins=*', '--window-position=404,38', '--window-size=1366,768']
        user_data_dir = /Users/ahmedzaidan/Library/Application Support/Google/Chrome
        uses_custom_data_dir = True, 'targets': [], 'info': None, '_target': None, '_process': None, '_process_pid': None, '_keep_user_data_dir': None, '_is_updating': <asyncio.locks.Event object at 0x1027f9280 [unset]>, 'connection': None}
DEBUG:nodriver.core.browser:BROWSER EXECUTABLE PATH: /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
INFO:nodriver.core.browser:starting
        executable :/Applications/Google Chrome.app/Contents/MacOS/Google Chrome

arguments:
--remote-allow-origins=*
        --no-first-run
        --no-service-autorun
        --no-default-browser-check
        --homepage=about:blank
        --no-pings
        --password-store=basic
        --disable-infobars
        --disable-breakpad
        --disable-dev-shm-usage
        --disable-session-crashed-bubble
        --disable-search-engine-choice-screen
        --user-data-dir=/Users/ahmedzaidan/Library/Application Support/Google/Chrome
        --disable-session-crashed-bubble
        --disable-features=IsolateOrigins,site-per-process
        --window-size=1366,768
        --window-position=404,38
        --profile-directory=Profile 4
        --remote-debugging-host=127.0.0.1
        --remote-debugging-port=59494
DEBUG:nodriver.core.browser:could not start
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/urllib/request.py", line 1344, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/opt/anaconda3/lib/python3.12/http/client.py", line 1331, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/opt/anaconda3/lib/python3.12/http/client.py", line 1377, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/opt/anaconda3/lib/python3.12/http/client.py", line 1326, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/opt/anaconda3/lib/python3.12/http/client.py", line 1085, in _send_output
    self.send(msg)
  File "/opt/anaconda3/lib/python3.12/http/client.py", line 1029, in send
    self.connect()
  File "/opt/anaconda3/lib/python3.12/http/client.py", line 995, in connect
    self.sock = self._create_connection(
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/socket.py", line 852, in create_connection
    raise exceptions[0]
  File "/opt/anaconda3/lib/python3.12/socket.py", line 837, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/nodriver/core/browser.py", line 430, in start
    self.info = ContraDict(await self._http.get("version"), silent=True)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/nodriver/core/browser.py", line 916, in get
    return await self._request(endpoint)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/nodriver/core/browser.py", line 935, in _request
    response = await asyncio.get_running_loop().run_in_executor(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/nodriver/core/browser.py", line 936, in <lambda>
    None, lambda: urllib.request.urlopen(request, timeout=10)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/urllib/request.py", line 215, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/urllib/request.py", line 515, in open
    response = self._open(req, data)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/urllib/request.py", line 532, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/urllib/request.py", line 492, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/urllib/request.py", line 1373, in http_open
    return self.do_open(http.client.HTTPConnection, req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/urllib/request.py", line 1347, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 61] Connection refused>
22:38:27 - nodriver_client_4342676032 - ERROR - Failed to start browser: 
                ---------------------
                Failed to connect to browser
                ---------------------
                One of the causes could be when you are running as root.
                In that case you need to pass no_sandbox=True 
                
ERROR:nodriver_client_4342676032:Failed to start browser: 
                ---------------------
                Failed to connect to browser
                ---------------------
                One of the causes could be when you are running as root.
                In that case you need to pass no_sandbox=True 
                
22:38:27 - nodriver_client_4342676032 - ERROR - Failed to initialize browser client: 
                ---------------------
                Failed to connect to browser
                ---------------------
                One of the causes could be when you are running as root.
                In that case you need to pass no_sandbox=True 
                
ERROR:nodriver_client_4342676032:Failed to initialize browser client: 
                ---------------------
                Failed to connect to browser
                ---------------------
                One of the causes could be when you are running as root.
                In that case you need to pass no_sandbox=True 
```

**Comment by ultrafunkamsterdam** [comment]
Why TF are you using profile directory argument ?

**Comment by ak3zaidan** [comment]
@ultrafunkamsterdam I don't understand, I thought I have to and doing It this way works on Chromium (launches with the correct profile). My full profile path is `/Users/ahmedzaidan/Library/Application Support/Google/Chrome/Profile 4`. I pass the first part as the user data dir, and the last part `Profile 4` I pass as the specific profile to use. If I comment out this profile directory argument and run, then chrome literally launches with the pick profile menu and I still get the same failed to connect error.

**Comment by ultrafunkamsterdam** [comment]
You need to pass the user data folder as user data dir eg:

```await start(user_data_dir="c:/temp/user data")```

Where 
c:/temp/user data
Is a copy of "%localappdata%\google\chrome\user data"  

In case of windows. Use equivalent on other os.

The user data folder should CONTAIN, amongst others,  a folder called Default

**Comment by ultrafunkamsterdam** [comment]
Chromium has very different security configuration as chrome release.

**Comment by SamplesofCode** [comment]
This might be a different cause, but I found one Windows-specific reason for `Failed to connect to browser`.

On my machine, it failed when the profile folder was created with `mkdtemp()`, but worked when I created basically the same kind of folder with `mkdir()` instead. So it seems like the problem might be how Windows is handling the folder when it comes from `mkdtemp()`, not just the Chrome flags or the folder name.

I made a patch for it here:

- fork: https://github.com/SamplesofCode/nodriverTempDirFix/tree/main
- commit: `e38903cf9cbcd8df0e04dcb25799147274b10639`
