### ISSUE TITLE
execute_script gets detected

### ISSUE THREAD

**Issue by RaY3R** [ultrafunkamsterdam/undetected-chromedriver#34]
On websites protected by Distill, like endclothing, they can detect if you execute javascript from the method "execute_script" instead of executing it directly on the console. Is it possible to avoid this detection? I see that selenium applies some scripts before executing mine.
Thanks.

**Comment by null-routed** [comment]
Same for me. I'd be great if we could have a workaround for this.

**Comment by TJM4** [comment]
It looks like they can detect whenever any command is executed (not just execute_script). Even get_cookies() causes detection

**Comment by ultrafunkamsterdam** [comment]
smth is changed in either the last or the one before the last driver protocol/chrome. 25GB code source makes it hard to debug en build every time, but i'm busy working on it and if you find something let me know.

**Comment by ultrafunkamsterdam** [comment]
fixed in 1.5.0

**Comment by RaY3R** [comment]
Sorry, I don't want to bother you but actually I'm still having some problems doing fetch requests with the execute_script.
For example:  
`fetch("https://api2.endclothing.com/eu/rest/V1/end/catalog/link?link=/en-de/stone-island-knit-7215517b3-v0029.html")` 
is working fine if executed directly on the console and I get 200 but not with the selenium method (403 or 416).
Hoping it would be helpful for finding a solution.
