### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by FloppyDance** [ultrafunkamsterdam/undetected-chromedriver#423]
This is my script:

```
import undetected_chromedriver as uc
driver = uc.Chrome()
driver.get('https://nowsecure.nl')
```

I get this error:

```
RuntimeError       (note: full exception trace is shown but execution is paused at: <module>)

        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.   File "D:\Users\Mark\python scripts\test_2.py", line 2, in <module> (Current frame)
    driver = uc.Chrome()   File "<string>", line 1, in <module>
```

How do I solve this?

**Comment by BenoitYU** [comment]
I got the same issue when I call the `driver = uc.Chrome()`, this code is trying to create 2 driver objects then cause the error shown as above. Any suggestion would be appreciated.

**Comment by nluttikhuizen** [comment]
fixed it with this: 
importing the multiprocessing: 
`from multiprocessing import Process, freeze_support`

And adding this to my main code:
```
if __name__ == "__main__": 
  freeze_support()
```

**Comment by BenoitYU** [comment]
> 

Appreciate for your reply. I just tested your idea, but still get an error back, could you give me a couple of code examples to make sure I correctly understand your idea?

**Comment by FloppyDance** [comment]
@ultrafunkamsterdam What do you think about this?

**Comment by brandfocus** [comment]
@FloppyDance You need to call it outside the module e.g.

```
from multiprocessing import Process, freeze_support

def  fetch_page():

  uc.Chrome(executable_path=os.path.abspath("chromedriver"))

if __name__ == "__main__": 
  freeze_support()
  fetch_page()
```

**Comment by FloppyDance** [comment]
> from multiprocessing import Process, freeze_support
> 
> def fetch_page():
> 
>   uc.Chrome(executable_path=os.path.abspath("chromedriver"))
> 
> if __name__ == "__main__": 
>   freeze_support()
>   fetch_page()

Returns this:
filename = fspath(filename)  # Does type-checking of `filename`.
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by wael9999** [comment]
Hey, may I know what I did wrong, as I am getting the same error? My Code


import time
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC, wait
from selenium.webdriver.chrome.options import Options
from selenium.common.exceptions import TimeoutException
import smtplib
from email.message import EmailMessage
import mimetypes
from selenium.webdriver.common.action_chains import ActionChains
from selenium.common.exceptions import NoSuchElementException
from selenium.common.exceptions import StaleElementReferenceException
import random
from random import randint
import undetected_chromedriver as uc
from multiprocessing import Process, freeze_support



options = webdriver.ChromeOptions() 



options.add_argument("user-data-dir=C:\\Users\\Boss\\AppData\\Local\\Temp\\scoped_dir1684_1493345151\\Profile 1")

chrome_options = webdriver.ChromeOptions()
prefs = {"profile.managed_default_content_settings.images": 2}
chrome_options.add_experimental_option("prefs", prefs)

browser = uc.Chrome(executable_path="C:/webdriver/chrome/chromedriver.exe", chrome_options=options)
if __name__ == "__main__": 
  freeze_support()
browser.get("https://www.instagram.com/p/CSJ7718jCbj/")

mylist = ["1", "2"]
def repeat():
    while 1 == 1: 
     
     password = WebDriverWait(browser, 10000).until(
     EC.presence_of_element_located((By.CLASS_NAME, 'Ypffh'))
     )
     time.sleep(3)  
     password.click()
     password=browser.find_element_by_class_name('Ypffh')
     password.click()
     time.sleep(16)
     password.send_keys(random.choice(mylist), Keys.ENTER)

     time.sleep(randint(160,250))
repeat()

**Comment by ultrafunkamsterdam** [comment]
almost everything.
to begin with you shouldn't add the paths for executable. start with examples given in readme instead of raising an issue.  thank you

**Comment by FloppyDance** [comment]
@ultrafunkamsterdam Actually I'm using the example in the readme, but it's not working.

```
import undetected_chromedriver.v2 as uc
driver = uc.Chrome()
driver.get('https://nowsecure.nl')  # known url using cloudflare's "under attack mode"
```

This script returns the above error.

Furthermore, the link in the Usage paragraph of the readme document is broken.

**Comment by BenoitYU** [comment]
> @FloppyDance You need to call it outside the module e.g.
> 
> ```
> from multiprocessing import Process, freeze_support
> 
> def fetch_page():
> 
>   uc.Chrome(executable_path=os.path.abspath("chromedriver"))
> 
> if __name__ == "__main__": 
>   freeze_support()
>   fetch_page()
> ```

Appreciate for the reply, I tested on 2 of my PCs with the way you proposed and thing is weird: on my working PC, it works, while with error return back on my individual PC. So I would dive into the issue and try to find out why. 
@FloppyDance, it seems like there is a link with PC's system language, because sometimes part of files in the package is not decoded correctly, I have fixed part of issues before which was caused by decode utf-8, gbk etc, hope this could give you some ideas on that.

**Comment by FloppyDance** [comment]
@BenoitYU What should I do? In the readme there are no references to system language.
I opened this issue hoping that @ultrafunkamsterdam would provide a solution, but apparently he doesn't give a fig about this.

**Comment by BenoitYU** [comment]
what is your current system language? try to config it into English if it's not the case,  and then check if it works

**Comment by FloppyDance** [comment]
I cannot change my system language just because this module is not working properly...

**Comment by BenoitYU** [comment]
I see, but from my side, the main difference I could tell so far between my 2 PCs is the system language, that's why I suggested that to you. Maybe I need try to change my own PC's language and see if it works.

**Comment by BenoitYU** [comment]
by the way, what's your current system language?

**Comment by FloppyDance** [comment]
It's Italian
